"""Enum-классы для моделей системы ЕХ:СИБ."""
import enum


class InspectionSource(str, enum.Enum):
    """Источник создания проверки (п. 5.1.1 ТЗ)."""
    MOBILE = "mobile"  # Мобильное приложение Inspectra
    WEB = "web"        # Веб-интерфейс ЕХ:СИБ


class InspectionStatus(str, enum.Enum):
    """Статус проверки (п. 5.3 ТЗ)."""
    DRAFT = "draft"           # Черновик (редактируется)
    SUBMITTED = "submitted"   # Завершена (доступна всем)
    APPROVED = "approved"     # Утверждена (для служебного использования)


class PlanStatus(str, enum.Enum):
    """Статус плана инспекций (п. 4.3 ТЗ)."""
    DRAFT = "draft"           # Черновик ( autogenerated в пятницу)
    APPROVED = "approved"     # Утверждён (понедельник до 10:00)
    ASSIGNED = "assigned"     # Доведён до инспекторов
    COMPLETED = "completed"   # Выполнен
    CANCELLED = "cancelled"   # Отменён


class NotificationType(str, enum.Enum):
    """Тип уведомления (п. 6.2 ТЗ)."""
    TOP_VIOLATION = "top_violation"
    GROSS_VIOLATION = "gross_violation"
    WORK_STOPPED = "work_stopped"
    INSPECTION_COMPLETED = "inspection_completed"
    PLAN_APPROVED = "plan_approved"
    NEW_ASSIGNMENT = "new_assignment"
    OVERDUE_INSPECTION = "overdue_inspection"
    VIOLATION_RESOLVED = "violation_resolved"


class NotificationChannel(str, enum.Enum):
    """Канал доставки уведомления (п. 6.1 ТЗ)."""
    EMAIL = "email"
    PUSH = "push"
    INTERNAL = "internal"