"""change inspection source and status to string with check constraints

Revision ID: 096143443761
Revises: 65037a8661e8
Create Date: 2026-07-27 10:56:26.859690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '096143443761'
down_revision: Union[str, None] = '65037a8661e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection', 'inspection_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Уникальный номер (INSP-560995)',
               existing_nullable=False)
    op.alter_column('inspection', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата проведения',
               existing_nullable=False)
    op.alter_column('inspection', 'pe_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Производственная единица',
               existing_nullable=False)
    op.alter_column('inspection', 'department_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Подразделение',
               existing_nullable=False)
    op.alter_column('inspection', 'inspector_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Инспектор',
               existing_nullable=False)
    op.alter_column('inspection', 'contractor_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='Подрядная организация')
    op.alter_column('inspection', 'plan_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Связь с планом (опционально)',
               existing_nullable=True)
    op.alter_column('inspection', 'work_location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Место производства работ',
               existing_nullable=False)
    op.alter_column('inspection', 'source',
               existing_type=postgresql.ENUM('MOBILE', 'WEB', name='inspectionsource'),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='Источник: mobile (Inspectra) / web (ЕХ:СИБ)',
               existing_nullable=False)
    op.alter_column('inspection', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', name='inspectionstatus'),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='Статус: draft / submitted / approved',
               existing_nullable=False)
    op.alter_column('inspection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_inspection_number'), 'inspection', type_='unique')
    op.drop_index(op.f('ix_inspection_inspection_number'), table_name='inspection')
    op.create_index(op.f('ix_inspection_inspection_number'), 'inspection', ['inspection_number'], unique=True)
    op.drop_constraint(op.f('inspection_contractor_id_fkey'), 'inspection', type_='foreignkey')
    op.create_foreign_key(None, 'inspection', 'contractor', ['contractor_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'inspection',
        'Шапка проверки',
        existing_comment='Шапка проверки (карта наблюдения)',
        schema=None
    )
    op.drop_column('inspection', 'updated_at')
    op.alter_column('violation_photo', 'violation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ссылка на нарушение',
               existing_nullable=False)
    op.alter_column('violation_photo', 'uploaded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Кто загрузил',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Путь к оригиналу в MinIO',
               existing_nullable=False)
    op.alter_column('violation_photo', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment=None,
               existing_comment='Путь к миниатюре в MinIO')
    op.alter_column('violation_photo', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Исходное имя файла',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер в байтах',
               existing_nullable=False)
    op.alter_column('violation_photo', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='MIME-тип (image/jpeg, image/png)',
               existing_nullable=False)
    op.alter_column('violation_photo', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Подпись к фото',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_latitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               comment=None,
               existing_comment='Широта',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_longitude',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               comment=None,
               existing_comment='Долгота',
               existing_nullable=True)
    op.alter_column('violation_photo', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               comment=None,
               existing_comment='Дата загрузки')
    op.drop_constraint(op.f('violation_photo_uploaded_by_fkey'), 'violation_photo', type_='foreignkey')
    op.create_foreign_key(None, 'violation_photo', 'user', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'violation_photo',
        existing_comment='Фотография нарушения (хранится в MinIO)',
        schema=None
    )
    op.drop_column('violation_photo', 'created_at')
    op.drop_column('violation_photo', 'updated_at')
    op.alter_column('violation_record', 'inspection_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ссылка на проверку',
               existing_nullable=False)
    op.alter_column('violation_record', 'work_type_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Вид работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'zpb_rule_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Нарушенное ЗПБ (опционально)',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_safe',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг «Все безопасно»',
               existing_nullable=False)
    op.alter_column('violation_record', 'violation_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание нарушения (обязательно, если is_safe=False)',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_gross_violation',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Грубейшее нарушение',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_work_stopped',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Остановка работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_top_violation',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Топ-нарушение (вычисляется автоматически)',
               existing_nullable=False)
    op.alter_column('violation_record', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Порядок строки',
               existing_nullable=False)
    op.drop_table_comment(
        'violation_record',
        existing_comment='Строка наблюдения (нарушение)',
        schema=None
    )
    op.drop_column('violation_record', 'created_at')
    op.drop_column('violation_record', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_record', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('violation_record', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'violation_record',
        'Строка наблюдения (нарушение)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('violation_record', 'order',
               existing_type=sa.INTEGER(),
               comment='Порядок строки',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_top_violation',
               existing_type=sa.BOOLEAN(),
               comment='Топ-нарушение (вычисляется автоматически)',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_work_stopped',
               existing_type=sa.BOOLEAN(),
               comment='Остановка работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_gross_violation',
               existing_type=sa.BOOLEAN(),
               comment='Грубейшее нарушение',
               existing_nullable=False)
    op.alter_column('violation_record', 'violation_description',
               existing_type=sa.TEXT(),
               comment='Описание нарушения (обязательно, если is_safe=False)',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_safe',
               existing_type=sa.BOOLEAN(),
               comment='Флаг «Все безопасно»',
               existing_nullable=False)
    op.alter_column('violation_record', 'zpb_rule_id',
               existing_type=sa.UUID(),
               comment='Нарушенное ЗПБ (опционально)',
               existing_nullable=True)
    op.alter_column('violation_record', 'work_type_id',
               existing_type=sa.UUID(),
               comment='Вид работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'inspection_id',
               existing_type=sa.UUID(),
               comment='Ссылка на проверку',
               existing_nullable=False)
    op.add_column('violation_photo', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('violation_photo', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'violation_photo',
        'Фотография нарушения (хранится в MinIO)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'violation_photo', type_='foreignkey')
    op.create_foreign_key(op.f('violation_photo_uploaded_by_fkey'), 'violation_photo', 'user', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('violation_photo', 'uploaded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Дата загрузки')
    op.alter_column('violation_photo', 'gps_longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               comment='Долгота',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               comment='Широта',
               existing_nullable=True)
    op.alter_column('violation_photo', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment='Подпись к фото',
               existing_nullable=True)
    op.alter_column('violation_photo', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               comment='MIME-тип (image/jpeg, image/png)',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_size',
               existing_type=sa.INTEGER(),
               comment='Размер в байтах',
               existing_nullable=False)
    op.alter_column('violation_photo', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Исходное имя файла',
               existing_nullable=False)
    op.alter_column('violation_photo', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='Путь к миниатюре в MinIO')
    op.alter_column('violation_photo', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Путь к оригиналу в MinIO',
               existing_nullable=False)
    op.alter_column('violation_photo', 'uploaded_by',
               existing_type=sa.UUID(),
               comment='Кто загрузил',
               existing_nullable=False)
    op.alter_column('violation_photo', 'violation_id',
               existing_type=sa.UUID(),
               comment='Ссылка на нарушение',
               existing_nullable=False)
    op.add_column('inspection', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'inspection',
        'Шапка проверки (карта наблюдения)',
        existing_comment='Шапка проверки',
        schema=None
    )
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.create_foreign_key(op.f('inspection_contractor_id_fkey'), 'inspection', 'contractor', ['contractor_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_inspection_inspection_number'), table_name='inspection')
    op.create_index(op.f('ix_inspection_inspection_number'), 'inspection', ['inspection_number'], unique=False)
    op.create_unique_constraint(op.f('uq_inspection_number'), 'inspection', ['inspection_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('inspection', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inspection', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', name='inspectionstatus'),
               comment='Статус: draft / submitted / approved',
               existing_nullable=False)
    op.alter_column('inspection', 'source',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MOBILE', 'WEB', name='inspectionsource'),
               comment='Источник: mobile (Inspectra) / web (ЕХ:СИБ)',
               existing_nullable=False)
    op.alter_column('inspection', 'work_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Место производства работ',
               existing_nullable=False)
    op.alter_column('inspection', 'plan_id',
               existing_type=sa.UUID(),
               comment='Связь с планом (опционально)',
               existing_nullable=True)
    op.alter_column('inspection', 'contractor_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Подрядная организация')
    op.alter_column('inspection', 'inspector_id',
               existing_type=sa.UUID(),
               comment='Инспектор',
               existing_nullable=False)
    op.alter_column('inspection', 'department_id',
               existing_type=sa.UUID(),
               comment='Подразделение',
               existing_nullable=False)
    op.alter_column('inspection', 'pe_id',
               existing_type=sa.UUID(),
               comment='Производственная единица',
               existing_nullable=False)
    op.alter_column('inspection', 'date',
               existing_type=sa.DATE(),
               comment='Дата проведения',
               existing_nullable=False)
    op.alter_column('inspection', 'inspection_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Уникальный номер (INSP-560995)',
               existing_nullable=False)
    # ### end Alembic commands ###