"""add client_id to inspection

Revision ID: 5474bd561756
Revises: 096143443761
Create Date: 2026-08-01 18:42:52.901762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5474bd561756'
down_revision: Union[str, None] = '096143443761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection', sa.Column('client_id', sa.String(length=36), nullable=False, comment='UUID клиента (web/mobile) для offline-идентификации и идемпотентности'))
    op.alter_column('inspection', 'id',
               existing_type=sa.UUID(),
               comment='Уникальный идентификатор проверки',
               existing_nullable=False)
    op.alter_column('inspection', 'inspection_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Уникальный номер проверки в формате INSP-YYMMDD-XXXX',
               existing_nullable=False)
    op.alter_column('inspection', 'date',
               existing_type=sa.DATE(),
               comment='Дата проведения проверки',
               existing_nullable=False)
    op.alter_column('inspection', 'pe_id',
               existing_type=sa.UUID(),
               comment='Производственная единица',
               existing_nullable=False)
    op.alter_column('inspection', 'department_id',
               existing_type=sa.UUID(),
               comment='Подразделение',
               existing_nullable=False)
    op.alter_column('inspection', 'inspector_id',
               existing_type=sa.UUID(),
               comment='Инспектор, проводивший проверку',
               existing_nullable=False)
    op.alter_column('inspection', 'contractor_id',
               existing_type=sa.UUID(),
               comment='Подрядная организация',
               existing_nullable=True)
    op.alter_column('inspection', 'work_location',
               existing_type=sa.VARCHAR(length=255),
               comment='Место производства работ',
               existing_nullable=False)
    op.alter_column('inspection', 'plan_id',
               existing_type=sa.UUID(),
               comment='Связь с планом инспекций',
               existing_nullable=True)
    op.alter_column('inspection', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='Источник: mobile или web',
               existing_nullable=False)
    op.alter_column('inspection', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Статус: draft, submitted, approved',
               existing_nullable=False)
    op.alter_column('inspection', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Дата и время создания',
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_inspection_contractor_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_date'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_inspection_number'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_source'), table_name='inspection')
    op.create_index(op.f('ix_inspection_client_id'), 'inspection', ['client_id'], unique=True)
    op.create_unique_constraint(None, 'inspection', ['inspection_number'])
    op.drop_table_comment(
        'inspection',
        existing_comment='Шапка проверки',
        schema=None
    )
    op.alter_column('violation_photo', 'violation_id',
               existing_type=sa.UUID(),
               comment='Ссылка на нарушение',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Путь к оригиналу в MinIO',
               existing_nullable=False)
    op.alter_column('violation_photo', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='Путь к миниатюре в MinIO')
    op.alter_column('violation_photo', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Исходное имя файла',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_size',
               existing_type=sa.INTEGER(),
               comment='Размер файла в байтах',
               existing_nullable=False)
    op.alter_column('violation_photo', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               comment='MIME-тип',
               existing_nullable=False)
    op.alter_column('violation_photo', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment='Подпись к фото',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Широта',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Долгота',
               existing_nullable=True)
    op.alter_column('violation_photo', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='Дата загрузки')
    op.alter_column('violation_photo', 'uploaded_by',
               existing_type=sa.UUID(),
               comment='Кто загрузил',
               existing_nullable=False)
    op.drop_constraint(op.f('violation_photo_uploaded_by_fkey'), 'violation_photo', type_='foreignkey')
    op.create_foreign_key(None, 'violation_photo', 'user', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.alter_column('violation_record', 'inspection_id',
               existing_type=sa.UUID(),
               comment='Ссылка на проверку',
               existing_nullable=False)
    op.alter_column('violation_record', 'work_type_id',
               existing_type=sa.UUID(),
               comment='Вид работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_safe',
               existing_type=sa.BOOLEAN(),
               comment="Флаг 'Все безопасно'",
               existing_nullable=False)
    op.alter_column('violation_record', 'violation_description',
               existing_type=sa.TEXT(),
               comment='Описание нарушения',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_gross_violation',
               existing_type=sa.BOOLEAN(),
               comment="Флаг 'Грубейшее нарушение'",
               existing_nullable=False)
    op.alter_column('violation_record', 'is_work_stopped',
               existing_type=sa.BOOLEAN(),
               comment="Флаг 'Остановка работ'",
               existing_nullable=False)
    op.alter_column('violation_record', 'zpb_rule_id',
               existing_type=sa.UUID(),
               comment='Нарушенное ЗПБ',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_top_violation',
               existing_type=sa.BOOLEAN(),
               comment='Вычисляемое поле: ТОП-нарушение',
               existing_nullable=False)
    op.alter_column('violation_record', 'order',
               existing_type=sa.INTEGER(),
               comment='Порядок строки',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('violation_record', 'order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Порядок строки',
               existing_nullable=False)
    op.alter_column('violation_record', 'is_top_violation',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Вычисляемое поле: ТОП-нарушение',
               existing_nullable=False)
    op.alter_column('violation_record', 'zpb_rule_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Нарушенное ЗПБ',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_work_stopped',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Флаг 'Остановка работ'",
               existing_nullable=False)
    op.alter_column('violation_record', 'is_gross_violation',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Флаг 'Грубейшее нарушение'",
               existing_nullable=False)
    op.alter_column('violation_record', 'violation_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание нарушения',
               existing_nullable=True)
    op.alter_column('violation_record', 'is_safe',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="Флаг 'Все безопасно'",
               existing_nullable=False)
    op.alter_column('violation_record', 'work_type_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Вид работ',
               existing_nullable=False)
    op.alter_column('violation_record', 'inspection_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ссылка на проверку',
               existing_nullable=False)
    op.drop_constraint(None, 'violation_photo', type_='foreignkey')
    op.create_foreign_key(op.f('violation_photo_uploaded_by_fkey'), 'violation_photo', 'user', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('violation_photo', 'uploaded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Кто загрузил',
               existing_nullable=False)
    op.alter_column('violation_photo', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Дата загрузки')
    op.alter_column('violation_photo', 'gps_longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Долгота',
               existing_nullable=True)
    op.alter_column('violation_photo', 'gps_latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Широта',
               existing_nullable=True)
    op.alter_column('violation_photo', 'caption',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Подпись к фото',
               existing_nullable=True)
    op.alter_column('violation_photo', 'mime_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='MIME-тип',
               existing_nullable=False)
    op.alter_column('violation_photo', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Размер файла в байтах',
               existing_nullable=False)
    op.alter_column('violation_photo', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Исходное имя файла',
               existing_nullable=False)
    op.alter_column('violation_photo', 'thumbnail_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment=None,
               existing_comment='Путь к миниатюре в MinIO')
    op.alter_column('violation_photo', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Путь к оригиналу в MinIO',
               existing_nullable=False)
    op.alter_column('violation_photo', 'violation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ссылка на нарушение',
               existing_nullable=False)
    op.create_table_comment(
        'inspection',
        'Шапка проверки',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'inspection', type_='unique')
    op.drop_index(op.f('ix_inspection_client_id'), table_name='inspection')
    op.create_index(op.f('ix_inspection_source'), 'inspection', ['source'], unique=False)
    op.create_index(op.f('ix_inspection_inspection_number'), 'inspection', ['inspection_number'], unique=True)
    op.create_index(op.f('ix_inspection_date'), 'inspection', ['date'], unique=False)
    op.create_index(op.f('ix_inspection_contractor_id'), 'inspection', ['contractor_id'], unique=False)
    op.alter_column('inspection', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Дата и время создания',
               existing_server_default=sa.text('now()'))
    op.alter_column('inspection', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Статус: draft, submitted, approved',
               existing_nullable=False)
    op.alter_column('inspection', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Источник: mobile или web',
               existing_nullable=False)
    op.alter_column('inspection', 'plan_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Связь с планом инспекций',
               existing_nullable=True)
    op.alter_column('inspection', 'work_location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Место производства работ',
               existing_nullable=False)
    op.alter_column('inspection', 'contractor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Подрядная организация',
               existing_nullable=True)
    op.alter_column('inspection', 'inspector_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Инспектор, проводивший проверку',
               existing_nullable=False)
    op.alter_column('inspection', 'department_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Подразделение',
               existing_nullable=False)
    op.alter_column('inspection', 'pe_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Производственная единица',
               existing_nullable=False)
    op.alter_column('inspection', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата проведения проверки',
               existing_nullable=False)
    op.alter_column('inspection', 'inspection_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Уникальный номер проверки в формате INSP-YYMMDD-XXXX',
               existing_nullable=False)
    op.alter_column('inspection', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Уникальный идентификатор проверки',
               existing_nullable=False)
    op.drop_column('inspection', 'client_id')
    # ### end Alembic commands ###