"""add_inspection_tables

Revision ID: 5e285157b45f
Revises: b4f6f9a014a5
Create Date: 2026-07-24 10:58:29.732266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e285157b45f'
down_revision: Union[str, None] = 'b4f6f9a014a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection',
    sa.Column('inspection_number', sa.String(length=20), nullable=False, comment='Уникальный номер (INSP-560995)'),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата проведения'),
    sa.Column('work_location', sa.String(length=255), nullable=False, comment='Место производства работ'),
    sa.Column('source', sa.Enum('MOBILE', 'WEB', name='inspectionsource'), nullable=False, comment='Источник: mobile (Inspectra) / web (ЕХ:СИБ)'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', name='inspectionstatus'), nullable=False, comment='Статус: draft / submitted / approved'),
    sa.Column('pe_id', sa.UUID(), nullable=False, comment='Производственная единица'),
    sa.Column('department_id', sa.UUID(), nullable=False, comment='Подразделение'),
    sa.Column('inspector_id', sa.UUID(), nullable=False, comment='Инспектор'),
    sa.Column('contractor_id', sa.UUID(), nullable=False, comment='Подрядная организация'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pe_id'], ['pe.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_number', name='uq_inspection_number'),
    comment='Шапка проверки (карта наблюдения)'
    )
    op.create_index(op.f('ix_inspection_contractor_id'), 'inspection', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_inspection_date'), 'inspection', ['date'], unique=False)
    op.create_index(op.f('ix_inspection_department_id'), 'inspection', ['department_id'], unique=False)
    op.create_index(op.f('ix_inspection_id'), 'inspection', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_inspection_number'), 'inspection', ['inspection_number'], unique=False)
    op.create_index(op.f('ix_inspection_inspector_id'), 'inspection', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspection_pe_id'), 'inspection', ['pe_id'], unique=False)
    op.create_index(op.f('ix_inspection_source'), 'inspection', ['source'], unique=False)
    op.create_index(op.f('ix_inspection_status'), 'inspection', ['status'], unique=False)
    op.create_table('violation_record',
    sa.Column('is_safe', sa.Boolean(), nullable=False, comment='Флаг «Все безопасно»'),
    sa.Column('is_gross_violation', sa.Boolean(), nullable=False, comment='Грубейшее нарушение'),
    sa.Column('is_work_stopped', sa.Boolean(), nullable=False, comment='Остановка работ'),
    sa.Column('is_top_violation', sa.Boolean(), nullable=False, comment='Топ-нарушение (вычисляется автоматически)'),
    sa.Column('violation_description', sa.Text(), nullable=True, comment='Описание нарушения (обязательно, если is_safe=False)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Порядок строки'),
    sa.Column('inspection_id', sa.UUID(), nullable=False, comment='Ссылка на проверку'),
    sa.Column('work_type_id', sa.UUID(), nullable=False, comment='Вид работ'),
    sa.Column('zpb_rule_id', sa.UUID(), nullable=True, comment='Нарушенное ЗПБ (опционально)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zpb_rule_id'], ['zpb_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Строка наблюдения (нарушение)'
    )
    op.create_index(op.f('ix_violation_record_id'), 'violation_record', ['id'], unique=False)
    op.create_index(op.f('ix_violation_record_inspection_id'), 'violation_record', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_violation_record_is_top_violation'), 'violation_record', ['is_top_violation'], unique=False)
    op.create_index(op.f('ix_violation_record_work_type_id'), 'violation_record', ['work_type_id'], unique=False)
    op.create_index(op.f('ix_violation_record_zpb_rule_id'), 'violation_record', ['zpb_rule_id'], unique=False)
    op.create_table('violation_photo',
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Путь к оригиналу в MinIO'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=False, comment='Путь к миниатюре в MinIO'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Исходное имя файла'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Размер в байтах'),
    sa.Column('mime_type', sa.String(length=50), nullable=False, comment='MIME-тип (image/jpeg, image/png)'),
    sa.Column('caption', sa.String(length=500), nullable=True, comment='Подпись к фото'),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Широта'),
    sa.Column('gps_longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='Долгота'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False, comment='Дата загрузки'),
    sa.Column('violation_id', sa.UUID(), nullable=False, comment='Ссылка на нарушение'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False, comment='Кто загрузил'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['violation_id'], ['violation_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Фотография нарушения (хранится в MinIO)'
    )
    op.create_index(op.f('ix_violation_photo_id'), 'violation_photo', ['id'], unique=False)
    op.create_index(op.f('ix_violation_photo_uploaded_by'), 'violation_photo', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_violation_photo_violation_id'), 'violation_photo', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_photo_violation_id'), table_name='violation_photo')
    op.drop_index(op.f('ix_violation_photo_uploaded_by'), table_name='violation_photo')
    op.drop_index(op.f('ix_violation_photo_id'), table_name='violation_photo')
    op.drop_table('violation_photo')
    op.drop_index(op.f('ix_violation_record_zpb_rule_id'), table_name='violation_record')
    op.drop_index(op.f('ix_violation_record_work_type_id'), table_name='violation_record')
    op.drop_index(op.f('ix_violation_record_is_top_violation'), table_name='violation_record')
    op.drop_index(op.f('ix_violation_record_inspection_id'), table_name='violation_record')
    op.drop_index(op.f('ix_violation_record_id'), table_name='violation_record')
    op.drop_table('violation_record')
    op.drop_index(op.f('ix_inspection_status'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_source'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_pe_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_inspector_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_inspection_number'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_department_id'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_date'), table_name='inspection')
    op.drop_index(op.f('ix_inspection_contractor_id'), table_name='inspection')
    op.drop_table('inspection')
    # ### end Alembic commands ###