"""add_planning_and_notification_tables

Revision ID: 65037a8661e8
Revises: 5e285157b45f
Create Date: 2026-07-24 11:06:59.054360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65037a8661e8'
down_revision: Union[str, None] = '5e285157b45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_plan',
    sa.Column('week_start_date', sa.Date(), nullable=False, comment='Дата начала недели (понедельник)'),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ASSIGNED', 'COMPLETED', 'CANCELLED', name='planstatus'), nullable=False, comment='Статус: draft / approved / assigned / completed / cancelled'),
    sa.Column('created_by_id', sa.UUID(), nullable=False, comment='Кто создал/утвердил план'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='План инспекций на неделю'
    )
    op.create_index(op.f('ix_inspection_plan_created_by_id'), 'inspection_plan', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inspection_plan_status'), 'inspection_plan', ['status'], unique=False)
    op.create_index(op.f('ix_inspection_plan_week_start_date'), 'inspection_plan', ['week_start_date'], unique=True)
    op.create_table('notification',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Получатель'),
    sa.Column('type', sa.Enum('TOP_VIOLATION', 'GROSS_VIOLATION', 'WORK_STOPPED', 'INSPECTION_COMPLETED', 'PLAN_APPROVED', 'NEW_ASSIGNMENT', 'OVERDUE_INSPECTION', 'VIOLATION_RESOLVED', name='notificationtype'), nullable=False, comment='Тип уведомления (top_violation, gross_violation и т.д.)'),
    sa.Column('channel', sa.Enum('EMAIL', 'PUSH', 'INTERNAL', name='notificationchannel'), nullable=False, comment='Канал доставки: email, push, internal'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Заголовок'),
    sa.Column('message', sa.Text(), nullable=False, comment='Текст уведомления'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Прочитано'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Время фактической отправки'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Журнал уведомлений пользователей'
    )
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('user_pe_assignment',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Пользователь'),
    sa.Column('pe_id', sa.UUID(), nullable=False, comment='Производственная единица'),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='Действует с'),
    sa.Column('valid_to', sa.Date(), nullable=True, comment='Действует по (null = бессрочно)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pe_id'], ['pe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Назначение пользователя на ПЕ'
    )
    op.create_index(op.f('ix_user_pe_assignment_is_active'), 'user_pe_assignment', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_pe_assignment_pe_id'), 'user_pe_assignment', ['pe_id'], unique=False)
    op.create_index(op.f('ix_user_pe_assignment_user_id'), 'user_pe_assignment', ['user_id'], unique=False)
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.add_column('inspection', sa.Column('plan_id', sa.UUID(), nullable=True, comment='Связь с планом (опционально)'))
    op.drop_index(op.f('ix_inspection_id'), table_name='inspection')
    op.create_index(op.f('ix_inspection_plan_id'), 'inspection', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'inspection', 'inspection_plan', ['plan_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_pe_id'), table_name='pe')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_violation_photo_id'), table_name='violation_photo')
    op.drop_index(op.f('ix_violation_record_id'), table_name='violation_record')
    op.drop_index(op.f('ix_work_type_id'), table_name='work_type')
    op.drop_index(op.f('ix_zpb_rule_id'), table_name='zpb_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_zpb_rule_id'), 'zpb_rule', ['id'], unique=False)
    op.create_index(op.f('ix_work_type_id'), 'work_type', ['id'], unique=False)
    op.create_index(op.f('ix_violation_record_id'), 'violation_record', ['id'], unique=False)
    op.create_index(op.f('ix_violation_photo_id'), 'violation_photo', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_pe_id'), 'pe', ['id'], unique=False)
    op.drop_constraint(None, 'inspection', type_='foreignkey')
    op.drop_index(op.f('ix_inspection_plan_id'), table_name='inspection')
    op.create_index(op.f('ix_inspection_id'), 'inspection', ['id'], unique=False)
    op.drop_column('inspection', 'plan_id')
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.drop_index(op.f('ix_user_pe_assignment_user_id'), table_name='user_pe_assignment')
    op.drop_index(op.f('ix_user_pe_assignment_pe_id'), table_name='user_pe_assignment')
    op.drop_index(op.f('ix_user_pe_assignment_is_active'), table_name='user_pe_assignment')
    op.drop_table('user_pe_assignment')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_inspection_plan_week_start_date'), table_name='inspection_plan')
    op.drop_index(op.f('ix_inspection_plan_status'), table_name='inspection_plan')
    op.drop_index(op.f('ix_inspection_plan_created_by_id'), table_name='inspection_plan')
    op.drop_table('inspection_plan')
    # ### end Alembic commands ###