"""add_reference_tables

Revision ID: fd201152c4e8
Revises: 
Create Date: 2026-07-24 10:41:55.199944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd201152c4e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название подрядчика'),
    sa.Column('inn', sa.String(length=20), nullable=True, comment='ИНН'),
    sa.Column('contact_person', sa.String(length=255), nullable=True, comment='Контактное лицо'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Телефон'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_is_active'), 'contractor', ['is_active'], unique=False)
    op.create_table('pe',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название ПЕ'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Код ПЕ'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_pe_id'), 'pe', ['id'], unique=False)
    op.create_index(op.f('ix_pe_is_active'), 'pe', ['is_active'], unique=False)
    op.create_table('work_type',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название вида работ'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Код'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_work_type_id'), 'work_type', ['id'], unique=False)
    op.create_index(op.f('ix_work_type_is_active'), 'work_type', ['is_active'], unique=False)
    op.create_table('zpb_rule',
    sa.Column('number', sa.Integer(), nullable=False, comment='Номер правила (1-7)'),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Краткое название'),
    sa.Column('description', sa.Text(), nullable=True, comment='Полное описание'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_zpb_rule_id'), 'zpb_rule', ['id'], unique=False)
    op.create_index(op.f('ix_zpb_rule_is_active'), 'zpb_rule', ['is_active'], unique=False)
    op.create_table('department',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название подразделения'),
    sa.Column('pe_id', sa.UUID(), nullable=False, comment='ПЕ'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активно'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pe_id'], ['pe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'pe_id', name='uq_department_name_pe'),
    comment='Подразделения (привязаны к ПЕ)'
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_department_is_active'), 'department', ['is_active'], unique=False)
    op.create_index(op.f('ix_department_pe_id'), 'department', ['pe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_pe_id'), table_name='department')
    op.drop_index(op.f('ix_department_is_active'), table_name='department')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_zpb_rule_is_active'), table_name='zpb_rule')
    op.drop_index(op.f('ix_zpb_rule_id'), table_name='zpb_rule')
    op.drop_table('zpb_rule')
    op.drop_index(op.f('ix_work_type_is_active'), table_name='work_type')
    op.drop_index(op.f('ix_work_type_id'), table_name='work_type')
    op.drop_table('work_type')
    op.drop_index(op.f('ix_pe_is_active'), table_name='pe')
    op.drop_index(op.f('ix_pe_id'), table_name='pe')
    op.drop_table('pe')
    op.drop_index(op.f('ix_contractor_is_active'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_table('contractor')
    # ### end Alembic commands ###